#File name: deploy.yml
#Author: Kyle McColgan
#Date: 1 October 2026
#Description: This file contains the workflow for GitHub Actions and the GitHub Pages deployment processes.

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # For push to the gh-pages branch...

#Prevents multiple concurrent deployments from stepping on each other...
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install package dependencies
        run: npm ci #Safer/faster alternative to npm install in CI environments.

      - name: Build the project
        run: npm run build  # Vite outputs to ./dist directory...

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages                # The branch to push to.
          folder: dist                    # Vite's build folder is dist.
          token: ${{ secrets.GH_TOKEN }}  # Using the PAT secret for deployment.

